name: 'K8s set context action'
description: 'GitHub Action for setting context before deploying to Kubernetes clusters'
inputs:
  kubeconfig:  # Setup the KUBECONFIG
    description: 'The content of KUBECONFIG, like $HOME/.kube/config'
    required: true
    default: ''
branding:
  color: 'blue'
  icon: 'terminal'
runs:
  using: 'node12'
  main: 'dist/index.js'