name: 'Common Kubernetes set context'
description: 'GitHub Action for setting context before deploying to Kubernetes clusters'
inputs:
  kubeconfig:  # Setup the KUBECONFIG
    description: 'The content of KUBECONFIG, like $HOME/.kube/config'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'src/index.js'